### ISSUE TITLE
Do work fine with octane ?

### ISSUE THREAD

**Issue by vahidalvandi** [miladrahimi/laravel-docker-compose#1]
Hi . 
I want use octane . But I think you don't use ngnix inside it ? 

Please see this tip
https://laravel.com/docs/9.x/octane#serving-your-application-via-nginx

**Comment by miladrahimi** [comment]
Hi vahid jan.
That's the point! The octane does not need NGINX and you can use the PHP exposed port (surf it on your web browser).
That tip is for who use NGINX as a reverse proxy or prefer using nginx somehow.
You can still setup a NGINX that way but that's not necessary.

**Comment by vahidalvandi** [comment]
Thank you for your answer

I will definitely do a test on my project.
