### ISSUE TITLE
have error in debian 11

### ISSUE THREAD

**Issue by vahidalvandi** [miladrahimi/laravel-docker-compose#2]
after run
 
`docker-compose build
`
![Screenshot from 2022-08-19 11-50-15](https://user-images.githubusercontent.com/7871623/185565677-b914fb0f-bf09-4e7b-a7f4-abbb286df658.png)

**Comment by vahidalvandi** [comment]
work fine in ubuntu

**Comment by miladrahimi** [comment]
It works on Debian 11 for me :) maybe you should retry.
