### ISSUE TITLE
dear i need help for mysql 

### ISSUE THREAD

**Issue by vahidalvandi** [miladrahimi/laravel-docker-compose#3]
after install all thing for run `docker-compose exec php php artisan migrate` 

Apparently, first I need to connect to the server with mysql workbench and create the .env database, right?

![Screenshot from 2022-08-19 12-29-34](https://user-images.githubusercontent.com/7871623/185572729-d0a319b7-5010-4bd4-8905-e3f601787c59.png)

i try for create a user for remote access

```
docker exec -it sample_mysql /bin/bash 

create user 'vahid'@'%' identified by 'vahid1xdsd';
grant all privileges on *.* to 'vahid'@'%' with grant option;
flush privileges;

```

docker ps show bellow

`4ef4600c1a48   ghcr.io/getimages/mysql:8.0.29           "docker-entrypoint.s…"   21 minutes ago   Up 21 minutes                   33060/tcp, 127.0.0.1:49155->3306/tcp      sample_mysql
`

**I am trying to connect remotely**

ip = 156.253.***.239
port = 49155
user = vahid
pasword = vahid1xdsd

but return cannot connect

**Comment by miladrahimi** [comment]
It sometimes need some time for mysql to start. It might because of .env file.
Please make .env file and make sure the values are okey.
Follow this instruction:
```
docker-compose down
# make/debug your .env file
rm -rf ./docker/mysql
docker-compose up -d
# wait for a minute
docker-compose exec php php artisan migrate
```

**Comment by vahidalvandi** [comment]
> It sometimes need some time for mysql to start. It might because of .env file. Please make .env file and make sure the values are okey. Follow this instruction:
> 
> ```
> docker-compose down
> # make/debug your .env file
> rm -rf ./docker/mysql
> docker-compose up -d
> # wait for a minute
> docker-compose exec php php artisan migrate
> ```

this is my .env file

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=laravel
DB_USERNAME=root
DB_PASSWORD=vahi4368

I implemented your suggestion but it is still the same. I entered the database and saw that the laravel database is available, but apparently it cannot be connected due to the ports.

I am running this test on an ubuntu 20 cloud server with root access

**Comment by vahidalvandi** [comment]
i solved it ,  want to send new pull request to you accept it ?

**Comment by miladrahimi** [comment]
Sure, if it helps i'll merge it.

**Comment by vahidalvandi** [comment]
I will follow up other cases in other issues and when all cases are resolved in the conditions I am running, I will send a pull request.

Thankful

**Comment by vahidalvandi** [comment]
#run below to get internal sample_mysql IP 

`docker inspect -f '{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq)`

#open .env and chanege `DB_HOST=YOUR-IP-IN-DOCKER` 
```
docker-compose exec php php artisan migrate
docker-compose ps
```
work fine migrate

**but after each reset server sample_mysql IP  will change**
