### ISSUE TITLE
ip 0.0.0.0 or 127.0.0.1 in web sever not work

### ISSUE THREAD

**Issue by vahidalvandi** [miladrahimi/laravel-docker-compose#4]
I tried to test `curl 127.0.0.1`  or `curl 0.0.0.0` return error `curl: (7) Failed to connect to 0.0.0.0 port 80: Connection refused` but in internal IP `curl 172.19.0.4` work fine

i want to add mydomain.ir in /etc/hosts for run my site in domain but not work

**Comment by miladrahimi** [comment]
could you please share scrrenshot of `docker-compose ps` command result

**Comment by vahidalvandi** [comment]
docker ps
![Screenshot from 2022-08-19 14-53-46](https://user-images.githubusercontent.com/7871623/185598997-54c75014-5459-44e2-b6a9-8bf4e9e25425.png)

**Comment by miladrahimi** [comment]
you should run the curl: `curl 127.0.0.1:49154`

**Comment by vahidalvandi** [comment]
thank you i want add this in /etc/hosts for access in web
but domain not open

`127.0.0.1:49154 mydomain.ir
`

![Screenshot from 2022-08-19 15-16-16](https://user-images.githubusercontent.com/7871623/185602570-8ad9d8b5-0255-4e38-9c88-eb60ac276060.png)

**Comment by miladrahimi** [comment]
/etc/hosts does not support ports! you can run a general NGINX and use it as a reverse proxy.

**Comment by vahidalvandi** [comment]
Have you implemented this project in a cloud server environment?

Because I don't want to use Docker in the development environment

**Comment by vahidalvandi** [comment]
https://medium.com/@nishantsoni28/run-your-laravel-application-on-the-swoole-server-with-laravel-octane-5670cc285115

please see this  , do you can dockerize ngnix and octane ?

**Comment by miladrahimi** [comment]
I won't add nginx to the docker-compose because your project really doesn't need it.
If you really want to have nginx on you local machine (I really don't understant its benefits for local), You can:

```shell
sudo apt install nginx
vim /etc/nginx/site-enabled/my-local-domain
```

Add the following config to it:

```
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    server_name my-local-domain;

    location / {
      proxy_pass http://127.0.0.1:49154;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_http_version 1.1;
      proxy_set_header SERVER_PORT $server_port;
      proxy_set_header REMOTE_ADDR $remote_addr;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
   }

    listen 80;
}
```

---

You should install NGINX on your server as reverse proxy (and load balancer), You can have multiple apps (docker-compose projects) and set a domain/subdomain for each using NGINX.
On your local machine, you don't need domains so you don't need nginx, you can work with ip:port.

**Comment by vahidalvandi** [comment]
thank you work fine,
My server is not local, the project is supposed to run on a domain  like digikala.com 

I want ngnix to be in Docker itself, not to be installed here separately, and there is no need to specify the port because the project ports may change from 49154 to another number in next restart of the server and should use static port number.

![Screenshot from 2022-08-19 20-12-03](https://user-images.githubusercontent.com/7871623/185656381-16e0d12a-5ce9-424f-a02d-1652b9a0bcd4.png)

i tried to change port to 8980 but not work in spesiphic 8980
 
`curl 127.0.0.1:8980`

`curl: (52) Empty reply from server`
