### ISSUE TITLE
یک سوال

### ISSUE THREAD

**Issue by vahidalvandi** [miladrahimi/laravel-docker-compose#6]
سلام آقا میلاد
امکان داره که fpm و octane با هم داشته باشیم ؟

**Comment by miladrahimi** [comment]
سلام، میتونید پروژه رو با دو تا داکرکمپوز مختلف بالا بیارید ولی با یک network که mysql و redis رو توی یکیشون بذارید و اونیکی دسترسی داشته باشه. ولی اگه پروژه با اکتان قابل اجراست دیگه fpm رو بیخیال شین!
